Repository janus-idp/operator, pull requests merged in 2024-06, with the labels that each got.

#368 external db documentation
  docs/external-db.md
Labels: lgtm, approved

#372 added telemetry opt-in banner
  .rhdh/bundle/manifests/rhdh-operator.csv.yaml
  README.md
  bundle/manifests/backstage-operator.clusterserviceversion.yaml
  config/manifests/bases/backstage-operator.clusterserviceversion.yaml
Labels: lgtm, approved, do-not-merge/hold

#376 Fix version number in `skipRange` and `name` fields in base CSV
  config/manifests/bases/backstage-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#369 fix: Make sure to use backward-compatible names for resources created by the operator [RHIDP-2432]
  controllers/backstage_controller.go
  examples/bs-existing-secret.yaml
  integration_tests/db_test.go
  integration_tests/default-config_test.go
  integration_tests/testdata/raw-statefulset.yaml
  pkg/model/db-secret.go
  pkg/model/db-secret_test.go
  pkg/model/db-service.go
  pkg/model/db-statefulset.go
  pkg/utils/utils.go
Labels: lgtm, approved

#373 local to external db migration guide
  docs/db_migration.md
  hack/db_copy.sh
Labels: lgtm, approved

#371 Make a default db-service headless and use it as a serviceName for StatefulSet
  bundle/manifests/backstage-default-config_v1_configmap.yaml
  config/manager/default-config/db-service-hl.yaml
  config/manager/default-config/db-service.yaml
  config/manager/default-config/db-statefulset.yaml
  config/manager/kustomization.yaml
  docs/admin.md
  pkg/model/db-service.go
  pkg/model/db-statefulset.go
  pkg/model/db-statefulset_test.go
Labels: lgtm, approved

#380 [1.2.x] Make a default db-service headless and use it as a serviceName for StatefulSet
  bundle/manifests/backstage-default-config_v1_configmap.yaml
  config/manager/default-config/db-service-hl.yaml
  config/manager/default-config/db-service.yaml
  config/manager/default-config/db-statefulset.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/backstage-operator.clusterserviceversion.yaml
  docs/admin.md
  pkg/model/db-service.go
  pkg/model/db-statefulset.go
  pkg/model/db-statefulset_test.go
Labels: lgtm, approved

#379 ci: Run Nightly job against the `1.2.x` branch as well and skip job if operator image has expired
  .github/workflows/nightly.yaml
Labels: lgtm, approved

#381 Notify about dynamic plugin's file name constraints.
  pkg/model/dynamic-plugins.go
  pkg/model/dynamic-plugins_test.go
Labels: lgtm, approved

#384 fix: Fix reconciliation error preventing existing Backstage operands from being upgraded when the operator is upgraded from `1.1.x` [RHIDP-2597]
  .github/workflows/nightly.yaml
  Makefile
  controllers/backstage_controller.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/e2e_upgrade_test.go
  tests/e2e/testdata/backstage-operator-0.1.3.yaml
Labels: lgtm, approved

#387 fixed telemetry url
  .rhdh/bundle/manifests/rhdh-operator.csv.yaml
Labels: approved

#391 chore(CI): Skip the Operator Upgrade tests if the image for the current branch has expired
  .github/workflows/nightly.yaml
Labels: lgtm, approved
